language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add rustfmt || true
  - rustup component add clippy || true
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
  - cargo test --verbose --workspace --no-default-features
  - which cargo-fmt && cargo fmt --all -- --check
  - which cargo-clippy && cargo clippy --workspace -- -D warnings
jobs:
  fast_finish: true
