[package]
name = "ioslice"
version = "0.1.0"
authors = ["4lDO2 <4lDO2@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = ["libc"]
nightly = []

[dependencies]
libc = { version = "0.2", optional = true }

[dev-dependencies]
libc = "0.2"
